### ISSUE TITLE
Could not update ENVs on server

### ISSUE THREAD

**Issue by marcus-franzen** [zauberware/capistrano-ops#19]
** Execute figaro_yml:check_figaro_file_exists
cap aborted!
NoMethodError: undefined method `exists?' for File:Class (NoMethodError)

    next if File.exists?(figaro_yml_local_path)
                ^^^^^^^^
Did you mean?  exist?
/Users/marcusfranzen/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/capistrano-figaro-yml-1.0.5/lib/capistrano/tasks/figaro_yml.rake:14:in `block (2 levels) in <top (required)>'

**Comment by floriancrusius** [comment]
This problem is now solved with v1.0.0, as capistrano-ops now includes the functionalities of capistrano-figaro-yml gem
so you can update to the v1.0.0 and remove the capistrano-figaro-yml gem
